import type { Metadata } from "next";
import "@/styles/globals.css";
import Navbar from "@/components/global/Navbar";
import { ThemeProvider } from "@/components/global/Provider";
import { Inter, DynaPuff } from "next/font/google";
import CursorEffect from "@/components/ui/CursorEffect";
import { Toaster } from 'sonner';
import { Footer } from "@/components/global/Footer";
import { Analytics } from "@vercel/analytics/react"
import { SpeedInsights } from "@vercel/speed-insights/next"
import VisitorTracker from "@/components/VisitorTracker";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

const dynaPuff = DynaPuff({
  subsets: ["latin"],
  variable: "--font-dynapuff",
  display: "swap",
  preload: true,
});

export const metadata: Metadata = {
  title: "Yusuf Jaelani",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className={`${inter.variable} ${dynaPuff.variable}`}>
      <body className="antialiased bg-sa-light-bg text-sa-light-accent dark:bg-sa-dark-bg dark:text-sa-dark-text-main">
        <Analytics />
        <SpeedInsights />
        <VisitorTracker />
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <Navbar />
     {children}
          <CursorEffect />
          <Footer />
        </ThemeProvider>
        <Toaster richColors position="top-right" />
      </body>
    </html>
  );
}
